import { z } from "zod";

export enum RussianState {
  Adygea = "Adygea",
  AltaiKrai = "Altai Krai",
  AltaiRepublic = "Altai Republic",
  AmurOblast = "Amur Oblast",
  ArkhangelskOblast = "Arkhangelsk Oblast",
  AstrakhanOblast = "Astrakhan Oblast",
  Bashkortostan = "Bashkortostan",
  BelgorodOblast = "Belgorod Oblast",
  Buryatia = "Buryatia",
  Chechnya = "Chechnya",
  ChelyabinskOblast = "Chelyabinsk Oblast",
  ChukchiAutonomousOkrug = "Chukchi Autonomous Okrug",
  Chuvashia = "Chuvashia",
  Dagestan = "Dagestan",
  Ingushetia = "Ingushetia",
  IrkutskOblast = "Irkutsk Oblast",
  IvanovoOblast = "Ivanovo Oblast",
  JewishAutonomousOblast = "Jewish Autonomous Oblast",
  KabardinoBalkaria = "Kabardino-Balkaria",
  KaliningradOblast = "Kaliningrad Oblast",
  Kalmykia = "Kalmykia",
  KamchatkaKrai = "Kamchatka Krai",
  Karelia = "Karelia",
  KemerovoOblast = "Kemerovo Oblast",
  KhabarovskKrai = "Khabarovsk Krai",
  Khakassia = "Khakassia",
  KomiRepublic = "Komi Republic",
  KostromaOblast = "Kostroma Oblast",
  KrasnodarKrai = "Krasnodar Krai",
  KrasnoyarskKrai = "Krasnoyarsk Krai",
  KurganOblast = "Kurgan Oblast",
  KurskOblast = "Kursk Oblast",
  LeningradOblast = "Leningrad Oblast",
  LipetskOblast = "Lipetsk Oblast",
  Moscow = "Moscow",
  MoscowOblast = "Moscow Oblast",
  MurmanskOblast = "Murmansk Oblast",
  NizhnyNovgorodOblast = "Nizhny Novgorod Oblast",
  NorthOssetia = "North Ossetia",
  NovgorodOblast = "Novgorod Oblast",
  NovosibirskOblast = "Novosibirsk Oblast",
  OmskOblast = "Omsk Oblast",
  OrenburgOblast = "Orenburg Oblast",
  OryolOblast = "Oryol Oblast",
  PenzaOblast = "Penza Oblast",
  PermKrai = "Perm Krai",
  PrimorskyKrai = "Primorsky Krai",
  PskovOblast = "Pskov Oblast",
  RostovOblast = "Rostov Oblast",
  RyazanOblast = "Ryazan Oblast",
  SaintPetersburg = "Saint Petersburg",
  SakhaRepublic = "Sakha Republic (Yakutia)",
  SakhalinOblast = "Sakhalin Oblast",
  SamaraOblast = "Samara Oblast",
  SaratovOblast = "Saratov Oblast",
  SmolenskOblast = "Smolensk Oblast",
  StavropolKrai = "Stavropol Krai",
  SverdlovskOblast = "Sverdlovsk Oblast",
  Tatarstan = "Tatarstan",
  TverOblast = "Tver Oblast",
  TomskOblast = "Tomsk Oblast",
  TulaOblast = "Tula Oblast",
  Udmurtia = "Udmurtia",
  UlyanovskOblast = "Ulyanovsk Oblast",
  VladimirOblast = "Vladimir Oblast",
  VolgogradOblast = "Volgograd Oblast",
  VologdaOblast = "Vologda Oblast",
  VoronezhOblast = "Voronezh Oblast",
  YamaloNenetsAutonomousOkrug = "Yamalo-Nenets Autonomous Okrug",
  YaroslavlOblast = "Yaroslavl Oblast",
  ZabaykalskyKrai = "Zabaykalsky Krai",
}

export const RussianStateAbbreviation = {
  Adygea: "AD",
  AltaiKrai: "ALT",
  AltaiRepublic: "ALTAI",
  AmurOblast: "AMU",
  ArkhangelskOblast: "ARK",
  AstrakhanOblast: "AST",
  Bashkortostan: "BA",
  BelgorodOblast: "BEL",
  Buryatia: "BU",
  Chechnya: "CE",
  ChelyabinskOblast: "CHE",
  ChukchiAutonomousOkrug: "CHUK",
  Chuvashia: "CHUV",
  Dagestan: "DA",
  Ingushetia: "ING",
  IrkutskOblast: "IRK",
  IvanovoOblast: "IVA",
  JewishAutonomousOblast: "JEO",
  KabardinoBalkaria: "KB",
  KaliningradOblast: "KAL",
  Kalmykia: "KALM",
  KamchatkaKrai: "KAM",
  Karelia: "KAR",
  KemerovoOblast: "KEM",
  KhabarovskKrai: "KHA",
  Khakassia: "KHAK",
  KomiRepublic: "KOM",
  KostromaOblast: "KOS",
  KrasnodarKrai: "KRN",
  KrasnoyarskKrai: "KRS",
  KurganOblast: "KUR",
  KurskOblast: "KURSK",
  LeningradOblast: "LEN",
  LipetskOblast: "LIP",
  Moscow: "MOS",
  MoscowOblast: "MOS",
  MurmanskOblast: "MUR",
  NizhnyNovgorodOblast: "NNV",
  NorthOssetia: "NO",
  NovgorodOblast: "NOV",
  NovosibirskOblast: "NOVOSIB",
  OmskOblast: "OMS",
  OrenburgOblast: "OREN",
  OryolOblast: "ORYL",
  PenzaOblast: "PEN",
  PermKrai: "PERM",
  PrimorskyKrai: "PRI",
  PskovOblast: "PSK",
  RostovOblast: "ROS",
  RyazanOblast: "RYA",
  SaintPetersburg: "SPB",
  SakhaRepublic: "SAK",
  SakhalinOblast: "SAKH",
  SamaraOblast: "SAM",
  SaratovOblast: "SAR",
  SmolenskOblast: "SMO",
  StavropolKrai: "STA",
  SverdlovskOblast: "SVE",
  Tatarstan: "TA",
  TverOblast: "TVE",
  TomskOblast: "TOM",
  TulaOblast: "TUL",
  Udmurtia: "UDM",
  UlyanovskOblast: "ULY",
  VladimirOblast: "VLA",
  VolgogradOblast: "VGG",
  VologdaOblast: "VLG",
  VoronezhOblast: "VOR",
  YamaloNenetsAutonomousOkrug: "YAM",
  YaroslavlOblast: "YAR",
  ZabaykalskyKrai: "ZAB",
};

export const RussianStateSchema = z
  .union([z.nativeEnum(RussianState), z.nativeEnum(RussianStateAbbreviation)])
  .transform((state) => {
    if (state in RussianStateAbbreviation) {
      return state;
    }
    return RussianStateAbbreviation[
      RussianState[
        state as keyof typeof RussianState
      ] as keyof typeof RussianStateAbbreviation
    ];
  });
