import { z } from "zod";

import { Continents } from "./continents";

export enum CountryName {
  Antarctica = "Antarctica",
  Algeria = "Algeria",
  Angola = "Angola",
  Benin = "Benin",
  Botswana = "Botswana",
  BurkinaFaso = "Burkina Faso",
  Burundi = "Burundi",
  CaboVerde = "Cabo Verde",
  Cameroon = "Cameroon",
  CentralAfricanRepublic = "Central African Republic",
  Chad = "Chad",
  Comoros = "Comoros",
  CongoBrazzaville = "Congo (Congo-Brazzaville)",
  CongoKinshasa = "Congo (Congo-Kinshasa)",
  Djibouti = "Djibouti",
  Egypt = "Egypt",
  EquatorialGuinea = "Equatorial Guinea",
  Eritrea = "Eritrea",
  Eswatini = "Eswatini (fmr. Swaziland)",
  Ethiopia = "Ethiopia",
  Gabon = "Gabon",
  Gambia = "Gambia",
  Ghana = "Ghana",
  Guinea = "Guinea",
  GuineaBissau = "Guinea-Bissau",
  IvoryCoast = "Ivory Coast",
  Kenya = "Kenya",
  Lesotho = "Lesotho",
  Liberia = "Liberia",
  Libya = "Libya",
  Madagascar = "Madagascar",
  Malawi = "Malawi",
  Mali = "Mali",
  Mauritania = "Mauritania",
  Mauritius = "Mauritius",
  Morocco = "Morocco",
  Mozambique = "Mozambique",
  Namibia = "Namibia",
  Niger = "Niger",
  Nigeria = "Nigeria",
  Rwanda = "Rwanda",
  SaoTomeAndPrincipe = "São Tomé and Príncipe",
  Senegal = "Senegal",
  Seychelles = "Seychelles",
  SierraLeone = "Sierra Leone",
  Somalia = "Somalia",
  SouthAfrica = "South Africa",
  SouthSudan = "South Sudan",
  Sudan = "Sudan",
  Tanzania = "Tanzania",
  Togo = "Togo",
  Tunisia = "Tunisia",
  Uganda = "Uganda",
  Zambia = "Zambia",
  Zimbabwe = "Zimbabwe",
  Afghanistan = "Afghanistan",
  Armenia = "Armenia",
  Azerbaijan = "Azerbaijan",
  Bahrain = "Bahrain",
  Bangladesh = "Bangladesh",
  Bhutan = "Bhutan",
  Brunei = "Brunei",
  Cambodia = "Cambodia",
  China = "China",
  Cyprus = "Cyprus",
  Georgia = "Georgia",
  India = "India",
  Indonesia = "Indonesia",
  Iran = "Iran",
  Iraq = "Iraq",
  Israel = "Israel",
  Japan = "Japan",
  Jordan = "Jordan",
  Kazakhstan = "Kazakhstan",
  Kuwait = "Kuwait",
  Kyrgyzstan = "Kyrgyzstan",
  Laos = "Laos",
  Lebanon = "Lebanon",
  Malaysia = "Malaysia",
  Maldives = "Maldives",
  Mongolia = "Mongolia",
  Myanmar = "Myanmar (formerly Burma)",
  Nepal = "Nepal",
  NorthKorea = "North Korea",
  Oman = "Oman",
  Pakistan = "Pakistan",
  PalestineState = "Palestine State",
  Philippines = "Philippines",
  Qatar = "Qatar",
  SaudiArabia = "Saudi Arabia",
  Singapore = "Singapore",
  SouthKorea = "South Korea",
  SriLanka = "Sri Lanka",
  Syria = "Syria",
  Tajikistan = "Tajikistan",
  Thailand = "Thailand",
  TimorLeste = "Timor-Leste",
  Turkmenistan = "Turkmenistan",
  UAE = "United Arab Emirates",
  Uzbekistan = "Uzbekistan",
  Vietnam = "Vietnam",
  Yemen = "Yemen",
  Albania = "Albania",
  Andorra = "Andorra",
  Austria = "Austria",
  Belarus = "Belarus",
  Belgium = "Belgium",
  BosniaHerzegovina = "Bosnia and Herzegovina",
  Bulgaria = "Bulgaria",
  Croatia = "Croatia",
  Czechia = "Czechia (Czech Republic)",
  Denmark = "Denmark",
  Estonia = "Estonia",
  Finland = "Finland",
  France = "France",
  Germany = "Germany",
  Greece = "Greece",
  Hungary = "Hungary",
  Iceland = "Iceland",
  Ireland = "Ireland",
  Italy = "Italy",
  Kosovo = "Kosovo",
  Latvia = "Latvia",
  Liechtenstein = "Liechtenstein",
  Lithuania = "Lithuania",
  Luxembourg = "Luxembourg",
  Malta = "Malta",
  Moldova = "Moldova",
  Monaco = "Monaco",
  Montenegro = "Montenegro",
  Netherlands = "Netherlands",
  NorthMacedonia = "North Macedonia",
  Norway = "Norway",
  Poland = "Poland",
  Portugal = "Portugal",
  Romania = "Romania",
  Russia = "Russia",
  SanMarino = "San Marino",
  Serbia = "Serbia",
  Slovakia = "Slovakia",
  Slovenia = "Slovenia",
  Spain = "Spain",
  Sweden = "Sweden",
  Switzerland = "Switzerland",
  Turkey = "Turkey",
  Ukraine = "Ukraine",
  UnitedKingdom = "United Kingdom",
  AntiguaAndBarbuda = "Antigua and Barbuda",
  Bahamas = "Bahamas",
  Barbados = "Barbados",
  Belize = "Belize",
  Canada = "Canada",
  CostaRica = "Costa Rica",
  Cuba = "Cuba",
  Dominica = "Dominica",
  DominicanRepublic = "Dominican Republic",
  ElSalvador = "El Salvador",
  Grenada = "Grenada",
  Guatemala = "Guatemala",
  Haiti = "Haiti",
  Honduras = "Honduras",
  Jamaica = "Jamaica",
  Mexico = "Mexico",
  Nicaragua = "Nicaragua",
  Panama = "Panama",
  SaintKittsAndNevis = "Saint Kitts and Nevis",
  SaintLucia = "Saint Lucia",
  SaintVincentAndGrenadines = "Saint Vincent and the Grenadines",
  TrinidadAndTobago = "Trinidad and Tobago",
  USA = "United States of America",
  Argentina = "Argentina",
  Bolivia = "Bolivia",
  Brazil = "Brazil",
  Chile = "Chile",
  Colombia = "Colombia",
  Ecuador = "Ecuador",
  Guyana = "Guyana",
  Paraguay = "Paraguay",
  Peru = "Peru",
  Suriname = "Suriname",
  Uruguay = "Uruguay",
  Venezuela = "Venezuela",
  Australia = "Australia",
  Fiji = "Fiji",
  Kiribati = "Kiribati",
  MarshallIslands = "Marshall Islands",
  Micronesia = "Micronesia",
  Nauru = "Nauru",
  NewZealand = "New Zealand",
  Palau = "Palau",
  PapuaNewGuinea = "Papua New Guinea",
  Samoa = "Samoa",
  SolomonIslands = "Solomon Islands",
  Tonga = "Tonga",
  Tuvalu = "Tuvalu",
  Vanuatu = "Vanuatu",
}

export enum CountryCode {
  Algeria = "DZ",
  Angola = "AO",
  Antarctica = "AQ",
  Benin = "BJ",
  Botswana = "BW",
  BurkinaFaso = "BF",
  Burundi = "BI",
  CaboVerde = "CV",
  Cameroon = "CM",
  CentralAfricanRepublic = "CF",
  Chad = "TD",
  Comoros = "KM",
  CongoBrazzaville = "CG",
  CongoKinshasa = "CD",
  Djibouti = "DJ",
  Egypt = "EG",
  EquatorialGuinea = "GQ",
  Eritrea = "ER",
  Eswatini = "SZ",
  Ethiopia = "ET",
  Gabon = "GA",
  Gambia = "GM",
  Ghana = "GH",
  Guinea = "GN",
  GuineaBissau = "GW",
  IvoryCoast = "CI",
  Kenya = "KE",
  Lesotho = "LS",
  Liberia = "LR",
  Libya = "LY",
  Madagascar = "MG",
  Malawi = "MW",
  Mali = "ML",
  Mauritania = "MR",
  Mauritius = "MU",
  Morocco = "MA",
  Mozambique = "MZ",
  Namibia = "NA",
  Niger = "NE",
  Nigeria = "NG",
  Rwanda = "RW",
  SaoTomeAndPrincipe = "ST",
  Senegal = "SN",
  Seychelles = "SC",
  SierraLeone = "SL",
  Somalia = "SO",
  SouthAfrica = "ZA",
  SouthSudan = "SS",
  Sudan = "SD",
  Tanzania = "TZ",
  Togo = "TG",
  Tunisia = "TN",
  Uganda = "UG",
  Zambia = "ZM",
  Zimbabwe = "ZW",
  Afghanistan = "AF",
  Armenia = "AM",
  Azerbaijan = "AZ",
  Bahrain = "BH",
  Bangladesh = "BD",
  Bhutan = "BT",
  Brunei = "BN",
  Cambodia = "KH",
  China = "CN",
  Cyprus = "CY",
  Georgia = "GE",
  India = "IN",
  Indonesia = "ID",
  Iran = "IR",
  Iraq = "IQ",
  Israel = "IL",
  Japan = "JP",
  Jordan = "JO",
  Kazakhstan = "KZ",
  Kuwait = "KW",
  Kyrgyzstan = "KG",
  Laos = "LA",
  Lebanon = "LB",
  Malaysia = "MY",
  Maldives = "MV",
  Mongolia = "MN",
  Myanmar = "MM",
  Nepal = "NP",
  NorthKorea = "KP",
  Oman = "OM",
  Pakistan = "PK",
  PalestineState = "PS",
  Philippines = "PH",
  Qatar = "QA",
  SaudiArabia = "SA",
  Singapore = "SG",
  SouthKorea = "KR",
  SriLanka = "LK",
  Syria = "SY",
  Tajikistan = "TJ",
  Thailand = "TH",
  TimorLeste = "TL",
  Turkmenistan = "TM",
  UAE = "AE",
  Uzbekistan = "UZ",
  Vietnam = "VN",
  Yemen = "YE",
  Albania = "AL",
  Andorra = "AD",
  Austria = "AT",
  Belarus = "BY",
  Belgium = "BE",
  BosniaHerzegovina = "BA",
  Bulgaria = "BG",
  Croatia = "HR",
  Czechia = "CZ",
  Denmark = "DK",
  Estonia = "EE",
  Finland = "FI",
  France = "FR",
  Germany = "DE",
  Greece = "GR",
  Hungary = "HU",
  Iceland = "IS",
  Ireland = "IE",
  Italy = "IT",
  Kosovo = "XK",
  Latvia = "LV",
  Liechtenstein = "LI",
  Lithuania = "LT",
  Luxembourg = "LU",
  Malta = "MT",
  Moldova = "MD",
  Monaco = "MC",
  Montenegro = "ME",
  Netherlands = "NL",
  NorthMacedonia = "MK",
  Norway = "NO",
  Poland = "PL",
  Portugal = "PT",
  Romania = "RO",
  Russia = "RU",
  SanMarino = "SM",
  Serbia = "RS",
  Slovakia = "SK",
  Slovenia = "SI",
  Spain = "ES",
  Sweden = "SE",
  Switzerland = "CH",
  Turkey = "TR",
  Ukraine = "UA",
  UnitedKingdom = "GB",
  AntiguaAndBarbuda = "AG",
  Bahamas = "BS",
  Barbados = "BB",
  Belize = "BZ",
  Canada = "CA",
  CostaRica = "CR",
  Cuba = "CU",
  Dominica = "DM",
  DominicanRepublic = "DO",
  ElSalvador = "SV",
  Grenada = "GD",
  Guatemala = "GT",
  Haiti = "HT",
  Honduras = "HN",
  Jamaica = "JM",
  Mexico = "MX",
  Nicaragua = "NI",
  Panama = "PA",
  SaintKittsAndNevis = "KN",
  SaintLucia = "LC",
  SaintVincentAndGrenadines = "VC",
  TrinidadAndTobago = "TT",
  USA = "US",
  Argentina = "AR",
  Bolivia = "BO",
  Brazil = "BR",
  Chile = "CL",
  Colombia = "CO",
  Ecuador = "EC",
  Guyana = "GY",
  Paraguay = "PY",
  Peru = "PE",
  Suriname = "SR",
  Uruguay = "UY",
  Venezuela = "VE",
  Australia = "AU",
  Fiji = "FJ",
  Kiribati = "KI",
  MarshallIslands = "MH",
  Micronesia = "FM",
  Nauru = "NR",
  NewZealand = "NZ",
  Palau = "PW",
  PapuaNewGuinea = "PG",
  Samoa = "WS",
  SolomonIslands = "SB",
  Tonga = "TO",
  Tuvalu = "TV",
  Vanuatu = "VU",
}

export const countryCodes = [
  CountryCode.Algeria,
  CountryCode.Angola,
  CountryCode.Antarctica,
  CountryCode.Benin,
  CountryCode.Botswana,
  CountryCode.BurkinaFaso,
  CountryCode.Burundi,
  CountryCode.CaboVerde,
  CountryCode.Cameroon,
  CountryCode.CentralAfricanRepublic,
  CountryCode.Chad,
  CountryCode.Comoros,
  CountryCode.CongoBrazzaville,
  CountryCode.CongoKinshasa,
  CountryCode.Djibouti,
  CountryCode.Egypt,
  CountryCode.EquatorialGuinea,
  CountryCode.Eritrea,
  CountryCode.Eswatini,
  CountryCode.Ethiopia,
  CountryCode.Gabon,
  CountryCode.Gambia,
  CountryCode.Ghana,
  CountryCode.Guinea,
  CountryCode.GuineaBissau,
  CountryCode.IvoryCoast,
  CountryCode.Kenya,
  CountryCode.Lesotho,
  CountryCode.Liberia,
  CountryCode.Libya,
  CountryCode.Madagascar,
  CountryCode.Malawi,
  CountryCode.Mali,
  CountryCode.Mauritania,
  CountryCode.Mauritius,
  CountryCode.Morocco,
  CountryCode.Mozambique,
  CountryCode.Namibia,
  CountryCode.Niger,
  CountryCode.Nigeria,
  CountryCode.Rwanda,
  CountryCode.SaoTomeAndPrincipe,
  CountryCode.Senegal,
  CountryCode.Seychelles,
  CountryCode.SierraLeone,
  CountryCode.Somalia,
  CountryCode.SouthAfrica,
  CountryCode.SouthSudan,
  CountryCode.Sudan,
  CountryCode.Tanzania,
  CountryCode.Togo,
  CountryCode.Tunisia,
  CountryCode.Uganda,
  CountryCode.Zambia,
  CountryCode.Zimbabwe,
  CountryCode.Afghanistan,
  CountryCode.Armenia,
  CountryCode.Azerbaijan,
  CountryCode.Bahrain,
  CountryCode.Bangladesh,
  CountryCode.Bhutan,
  CountryCode.Brunei,
  CountryCode.Cambodia,
  CountryCode.China,
  CountryCode.Cyprus,
  CountryCode.Georgia,
  CountryCode.India,
  CountryCode.Indonesia,
  CountryCode.Iran,
  CountryCode.Iraq,
  CountryCode.Israel,
  CountryCode.Japan,
  CountryCode.Jordan,
  CountryCode.Kazakhstan,
  CountryCode.Kuwait,
  CountryCode.Kyrgyzstan,
  CountryCode.Laos,
  CountryCode.Lebanon,
  CountryCode.Malaysia,
  CountryCode.Maldives,
  CountryCode.Mongolia,
  CountryCode.Myanmar,
  CountryCode.Nepal,
  CountryCode.NorthKorea,
  CountryCode.Oman,
  CountryCode.Pakistan,
  CountryCode.PalestineState,
  CountryCode.Philippines,
  CountryCode.Qatar,
  CountryCode.SaudiArabia,
  CountryCode.Singapore,
  CountryCode.SouthKorea,
  CountryCode.SriLanka,
  CountryCode.Syria,
  CountryCode.Tajikistan,
  CountryCode.Thailand,
  CountryCode.TimorLeste,
  CountryCode.Turkmenistan,
  CountryCode.UAE,
  CountryCode.Uzbekistan,
  CountryCode.Vietnam,
  CountryCode.Yemen,
  CountryCode.Albania,
  CountryCode.Andorra,
  CountryCode.Austria,
  CountryCode.Belarus,
  CountryCode.Belgium,
  CountryCode.BosniaHerzegovina,
  CountryCode.Bulgaria,
  CountryCode.Croatia,
  CountryCode.Czechia,
  CountryCode.Denmark,
  CountryCode.Estonia,
  CountryCode.Finland,
  CountryCode.France,
  CountryCode.Germany,
  CountryCode.Greece,
  CountryCode.Hungary,
  CountryCode.Iceland,
  CountryCode.Ireland,
  CountryCode.Italy,
  CountryCode.Kosovo,
  CountryCode.Latvia,
  CountryCode.Liechtenstein,
  CountryCode.Lithuania,
  CountryCode.Luxembourg,
  CountryCode.Malta,
  CountryCode.Moldova,
  CountryCode.Monaco,
  CountryCode.Montenegro,
  CountryCode.Netherlands,
  CountryCode.NorthMacedonia,
  CountryCode.Norway,
  CountryCode.Poland,
  CountryCode.Portugal,
  CountryCode.Romania,
  CountryCode.Russia,
  CountryCode.SanMarino,
  CountryCode.Serbia,
  CountryCode.Slovakia,
  CountryCode.Slovenia,
  CountryCode.Spain,
  CountryCode.Sweden,
  CountryCode.Switzerland,
  CountryCode.Turkey,
  CountryCode.Ukraine,
  CountryCode.UnitedKingdom,
  CountryCode.AntiguaAndBarbuda,
  CountryCode.Bahamas,
  CountryCode.Barbados,
  CountryCode.Belize,
  CountryCode.Canada,
  CountryCode.CostaRica,
  CountryCode.Cuba,
  CountryCode.Dominica,
  CountryCode.DominicanRepublic,
  CountryCode.ElSalvador,
  CountryCode.Grenada,
  CountryCode.Guatemala,
  CountryCode.Haiti,
  CountryCode.Honduras,
  CountryCode.Jamaica,
  CountryCode.Mexico,
  CountryCode.Nicaragua,
  CountryCode.Panama,
  CountryCode.SaintKittsAndNevis,
  CountryCode.SaintLucia,
  CountryCode.SaintVincentAndGrenadines,
  CountryCode.TrinidadAndTobago,
  CountryCode.USA,
  CountryCode.Argentina,
  CountryCode.Bolivia,
  CountryCode.Brazil,
  CountryCode.Chile,
  CountryCode.Colombia,
  CountryCode.Ecuador,
  CountryCode.Guyana,
  CountryCode.Paraguay,
  CountryCode.Peru,
  CountryCode.Suriname,
  CountryCode.Uruguay,
  CountryCode.Venezuela,
  CountryCode.Australia,
  CountryCode.Fiji,
  CountryCode.Kiribati,
  CountryCode.MarshallIslands,
  CountryCode.Micronesia,
  CountryCode.Nauru,
  CountryCode.NewZealand,
  CountryCode.Palau,
  CountryCode.PapuaNewGuinea,
  CountryCode.Samoa,
  CountryCode.SolomonIslands,
  CountryCode.Tonga,
  CountryCode.Tuvalu,
  CountryCode.Vanuatu,
] as const;

export const CountryNameToCodeMap = {
  [CountryName.Afghanistan]: CountryCode.Afghanistan,
  [CountryName.Albania]: CountryCode.Albania,
  [CountryName.Algeria]: CountryCode.Algeria,
  [CountryName.Andorra]: CountryCode.Andorra,
  [CountryName.Angola]: CountryCode.Angola,
  [CountryName.Antarctica]: CountryCode.Antarctica,
  [CountryName.AntiguaAndBarbuda]: CountryCode.AntiguaAndBarbuda,
  [CountryName.Argentina]: CountryCode.Argentina,
  [CountryName.Armenia]: CountryCode.Armenia,
  [CountryName.Australia]: CountryCode.Australia,
  [CountryName.Austria]: CountryCode.Austria,
  [CountryName.Azerbaijan]: CountryCode.Azerbaijan,
  [CountryName.Bahamas]: CountryCode.Bahamas,
  [CountryName.Bahrain]: CountryCode.Bahrain,
  [CountryName.Bangladesh]: CountryCode.Bangladesh,
  [CountryName.Barbados]: CountryCode.Barbados,
  [CountryName.Belarus]: CountryCode.Belarus,
  [CountryName.Belgium]: CountryCode.Belgium,
  [CountryName.Belize]: CountryCode.Belize,
  [CountryName.Benin]: CountryCode.Benin,
  [CountryName.Bhutan]: CountryCode.Bhutan,
  [CountryName.Bolivia]: CountryCode.Bolivia,
  [CountryName.BosniaHerzegovina]: CountryCode.BosniaHerzegovina,
  [CountryName.Botswana]: CountryCode.Botswana,
  [CountryName.Brazil]: CountryCode.Brazil,
  [CountryName.Brunei]: CountryCode.Brunei,
  [CountryName.Bulgaria]: CountryCode.Bulgaria,
  [CountryName.BurkinaFaso]: CountryCode.BurkinaFaso,
  [CountryName.Burundi]: CountryCode.Burundi,
  [CountryName.CaboVerde]: CountryCode.CaboVerde,
  [CountryName.Cambodia]: CountryCode.Cambodia,
  [CountryName.Cameroon]: CountryCode.Cameroon,
  [CountryName.Canada]: CountryCode.Canada,
  [CountryName.CentralAfricanRepublic]: CountryCode.CentralAfricanRepublic,
  [CountryName.Chad]: CountryCode.Chad,
  [CountryName.Chile]: CountryCode.Chile,
  [CountryName.China]: CountryCode.China,
  [CountryName.Colombia]: CountryCode.Colombia,
  [CountryName.Comoros]: CountryCode.Comoros,
  [CountryName.CongoBrazzaville]: CountryCode.CongoBrazzaville,
  [CountryName.CongoKinshasa]: CountryCode.CongoKinshasa,
  [CountryName.CostaRica]: CountryCode.CostaRica,
  [CountryName.Croatia]: CountryCode.Croatia,
  [CountryName.Cuba]: CountryCode.Cuba,
  [CountryName.Cyprus]: CountryCode.Cyprus,
  [CountryName.Czechia]: CountryCode.Czechia,
  [CountryName.Denmark]: CountryCode.Denmark,
  [CountryName.Djibouti]: CountryCode.Djibouti,
  [CountryName.Dominica]: CountryCode.Dominica,
  [CountryName.DominicanRepublic]: CountryCode.DominicanRepublic,
  [CountryName.Ecuador]: CountryCode.Ecuador,
  [CountryName.Egypt]: CountryCode.Egypt,
  [CountryName.ElSalvador]: CountryCode.ElSalvador,
  [CountryName.EquatorialGuinea]: CountryCode.EquatorialGuinea,
  [CountryName.Eritrea]: CountryCode.Eritrea,
  [CountryName.Estonia]: CountryCode.Estonia,
  [CountryName.Eswatini]: CountryCode.Eswatini,
  [CountryName.Ethiopia]: CountryCode.Ethiopia,
  [CountryName.Fiji]: CountryCode.Fiji,
  [CountryName.Finland]: CountryCode.Finland,
  [CountryName.France]: CountryCode.France,
  [CountryName.Gabon]: CountryCode.Gabon,
  [CountryName.Gambia]: CountryCode.Gambia,
  [CountryName.Georgia]: CountryCode.Georgia,
  [CountryName.Germany]: CountryCode.Germany,
  [CountryName.Ghana]: CountryCode.Ghana,
  [CountryName.Greece]: CountryCode.Greece,
  [CountryName.Grenada]: CountryCode.Grenada,
  [CountryName.Guatemala]: CountryCode.Guatemala,
  [CountryName.Guinea]: CountryCode.Guinea,
  [CountryName.GuineaBissau]: CountryCode.GuineaBissau,
  [CountryName.Guyana]: CountryCode.Guyana,
  [CountryName.Haiti]: CountryCode.Haiti,
  [CountryName.Honduras]: CountryCode.Honduras,
  [CountryName.Hungary]: CountryCode.Hungary,
  [CountryName.Iceland]: CountryCode.Iceland,
  [CountryName.India]: CountryCode.India,
  [CountryName.Indonesia]: CountryCode.Indonesia,
  [CountryName.Iran]: CountryCode.Iran,
  [CountryName.Iraq]: CountryCode.Iraq,
  [CountryName.Ireland]: CountryCode.Ireland,
  [CountryName.Israel]: CountryCode.Israel,
  [CountryName.Italy]: CountryCode.Italy,
  [CountryName.IvoryCoast]: CountryCode.IvoryCoast,
  [CountryName.Jamaica]: CountryCode.Jamaica,
  [CountryName.Japan]: CountryCode.Japan,
  [CountryName.Jordan]: CountryCode.Jordan,
  [CountryName.Kazakhstan]: CountryCode.Kazakhstan,
  [CountryName.Kenya]: CountryCode.Kenya,
  [CountryName.Kiribati]: CountryCode.Kiribati,
  [CountryName.Kosovo]: CountryCode.Kosovo,
  [CountryName.Kuwait]: CountryCode.Kuwait,
  [CountryName.Kyrgyzstan]: CountryCode.Kyrgyzstan,
  [CountryName.Laos]: CountryCode.Laos,
  [CountryName.Latvia]: CountryCode.Latvia,
  [CountryName.Lebanon]: CountryCode.Lebanon,
  [CountryName.Lesotho]: CountryCode.Lesotho,
  [CountryName.Liberia]: CountryCode.Liberia,
  [CountryName.Libya]: CountryCode.Libya,
  [CountryName.Liechtenstein]: CountryCode.Liechtenstein,
  [CountryName.Lithuania]: CountryCode.Lithuania,
  [CountryName.Luxembourg]: CountryCode.Luxembourg,
  [CountryName.Madagascar]: CountryCode.Madagascar,
  [CountryName.Malawi]: CountryCode.Malawi,
  [CountryName.Malaysia]: CountryCode.Malaysia,
  [CountryName.Maldives]: CountryCode.Maldives,
  [CountryName.Mali]: CountryCode.Mali,
  [CountryName.Malta]: CountryCode.Malta,
  [CountryName.MarshallIslands]: CountryCode.MarshallIslands,
  [CountryName.Mauritania]: CountryCode.Mauritania,
  [CountryName.Mauritius]: CountryCode.Mauritius,
  [CountryName.Mexico]: CountryCode.Mexico,
  [CountryName.Micronesia]: CountryCode.Micronesia,
  [CountryName.Moldova]: CountryCode.Moldova,
  [CountryName.Monaco]: CountryCode.Monaco,
  [CountryName.Mongolia]: CountryCode.Mongolia,
  [CountryName.Myanmar]: CountryCode.Myanmar,
  [CountryName.Montenegro]: CountryCode.Montenegro,
  [CountryName.Morocco]: CountryCode.Morocco,
  [CountryName.Mozambique]: CountryCode.Mozambique,
  [CountryName.Namibia]: CountryCode.Namibia,
  [CountryName.Nauru]: CountryCode.Nauru,
  [CountryName.Nepal]: CountryCode.Nepal,
  [CountryName.Netherlands]: CountryCode.Netherlands,
  [CountryName.NewZealand]: CountryCode.NewZealand,
  [CountryName.Nicaragua]: CountryCode.Nicaragua,
  [CountryName.Niger]: CountryCode.Niger,
  [CountryName.Nigeria]: CountryCode.Nigeria,
  [CountryName.NorthKorea]: CountryCode.NorthKorea,
  [CountryName.NorthMacedonia]: CountryCode.NorthMacedonia,
  [CountryName.Norway]: CountryCode.Norway,
  [CountryName.Oman]: CountryCode.Oman,
  [CountryName.PalestineState]: CountryCode.PalestineState,
  [CountryName.Pakistan]: CountryCode.Pakistan,
  [CountryName.Palau]: CountryCode.Palau,
  [CountryName.Panama]: CountryCode.Panama,
  [CountryName.PapuaNewGuinea]: CountryCode.PapuaNewGuinea,
  [CountryName.Paraguay]: CountryCode.Paraguay,
  [CountryName.Peru]: CountryCode.Peru,
  [CountryName.Philippines]: CountryCode.Philippines,
  [CountryName.Poland]: CountryCode.Poland,
  [CountryName.Portugal]: CountryCode.Portugal,
  [CountryName.Qatar]: CountryCode.Qatar,
  [CountryName.Romania]: CountryCode.Romania,
  [CountryName.Russia]: CountryCode.Russia,
  [CountryName.Rwanda]: CountryCode.Rwanda,
  [CountryName.SaintKittsAndNevis]: CountryCode.SaintKittsAndNevis,
  [CountryName.SaintLucia]: CountryCode.SaintLucia,
  [CountryName.SaintVincentAndGrenadines]:
    CountryCode.SaintVincentAndGrenadines,
  [CountryName.Samoa]: CountryCode.Samoa,
  [CountryName.SanMarino]: CountryCode.SanMarino,
  [CountryName.SaoTomeAndPrincipe]: CountryCode.SaoTomeAndPrincipe,
  [CountryName.SaudiArabia]: CountryCode.SaudiArabia,
  [CountryName.Senegal]: CountryCode.Senegal,
  [CountryName.Serbia]: CountryCode.Serbia,
  [CountryName.Seychelles]: CountryCode.Seychelles,
  [CountryName.SierraLeone]: CountryCode.SierraLeone,
  [CountryName.Singapore]: CountryCode.Singapore,
  [CountryName.Slovakia]: CountryCode.Slovakia,
  [CountryName.Slovenia]: CountryCode.Slovenia,
  [CountryName.SolomonIslands]: CountryCode.SolomonIslands,
  [CountryName.Somalia]: CountryCode.Somalia,
  [CountryName.SouthAfrica]: CountryCode.SouthAfrica,
  [CountryName.SouthKorea]: CountryCode.SouthKorea,
  [CountryName.SouthSudan]: CountryCode.SouthSudan,
  [CountryName.Spain]: CountryCode.Spain,
  [CountryName.SriLanka]: CountryCode.SriLanka,
  [CountryName.Sudan]: CountryCode.Sudan,
  [CountryName.Suriname]: CountryCode.Suriname,
  [CountryName.Sweden]: CountryCode.Sweden,
  [CountryName.Switzerland]: CountryCode.Switzerland,
  [CountryName.Syria]: CountryCode.Syria,
  [CountryName.Tajikistan]: CountryCode.Tajikistan,
  [CountryName.Tanzania]: CountryCode.Tanzania,
  [CountryName.Thailand]: CountryCode.Thailand,
  [CountryName.Togo]: CountryCode.Togo,
  [CountryName.Tonga]: CountryCode.Tonga,
  [CountryName.TrinidadAndTobago]: CountryCode.TrinidadAndTobago,
  [CountryName.Tunisia]: CountryCode.Tunisia,
  [CountryName.Turkmenistan]: CountryCode.Turkmenistan,
  [CountryName.Turkey]: CountryCode.Turkey,
  [CountryName.Tuvalu]: CountryCode.Tuvalu,
  [CountryName.TimorLeste]: CountryCode.TimorLeste,
  [CountryName.Uganda]: CountryCode.Uganda,
  [CountryName.Ukraine]: CountryCode.Ukraine,
  [CountryName.UAE]: CountryCode.UAE,
  [CountryName.UnitedKingdom]: CountryCode.UnitedKingdom,
  [CountryName.USA]: CountryCode.USA,
  [CountryName.Uruguay]: CountryCode.Uruguay,
  [CountryName.Uzbekistan]: CountryCode.Uzbekistan,
  [CountryName.Vanuatu]: CountryCode.Vanuatu,
  [CountryName.Venezuela]: CountryCode.Venezuela,
  [CountryName.Vietnam]: CountryCode.Vietnam,
  [CountryName.Yemen]: CountryCode.Yemen,
  [CountryName.Zambia]: CountryCode.Zambia,
  [CountryName.Zimbabwe]: CountryCode.Zimbabwe,
};

export const africaCountries = [
  {
    label: CountryName.Algeria,
    value: CountryNameToCodeMap[CountryName.Algeria],
  },
  {
    label: CountryName.Angola,
    value: CountryNameToCodeMap[CountryName.Angola],
  },
  { label: CountryName.Benin, value: CountryNameToCodeMap[CountryName.Benin] },
  {
    label: CountryName.Botswana,
    value: CountryNameToCodeMap[CountryName.Botswana],
  },
  {
    label: CountryName.BurkinaFaso,
    value: CountryNameToCodeMap[CountryName.BurkinaFaso],
  },
  {
    label: CountryName.Burundi,
    value: CountryNameToCodeMap[CountryName.Burundi],
  },
  {
    label: CountryName.CaboVerde,
    value: CountryNameToCodeMap[CountryName.CaboVerde],
  },
  {
    label: CountryName.Cameroon,
    value: CountryNameToCodeMap[CountryName.Cameroon],
  },
  {
    label: CountryName.CentralAfricanRepublic,
    value: CountryNameToCodeMap[CountryName.CentralAfricanRepublic],
  },
  { label: CountryName.Chad, value: CountryNameToCodeMap[CountryName.Chad] },
  {
    label: CountryName.Comoros,
    value: CountryNameToCodeMap[CountryName.Comoros],
  },
  {
    label: CountryName.CongoBrazzaville,
    value: CountryNameToCodeMap[CountryName.CongoBrazzaville],
  },
  {
    label: CountryName.CongoKinshasa,
    value: CountryNameToCodeMap[CountryName.CongoKinshasa],
  },
  {
    label: CountryName.Djibouti,
    value: CountryNameToCodeMap[CountryName.Djibouti],
  },
  { label: CountryName.Egypt, value: CountryNameToCodeMap[CountryName.Egypt] },
  {
    label: CountryName.EquatorialGuinea,
    value: CountryNameToCodeMap[CountryName.EquatorialGuinea],
  },
  {
    label: CountryName.Eritrea,
    value: CountryNameToCodeMap[CountryName.Eritrea],
  },
  {
    label: CountryName.Eswatini,
    value: CountryNameToCodeMap[CountryName.Eswatini],
  },
  {
    label: CountryName.Ethiopia,
    value: CountryNameToCodeMap[CountryName.Ethiopia],
  },
  { label: CountryName.Gabon, value: CountryNameToCodeMap[CountryName.Gabon] },
  {
    label: CountryName.Gambia,
    value: CountryNameToCodeMap[CountryName.Gambia],
  },
  { label: CountryName.Ghana, value: CountryNameToCodeMap[CountryName.Ghana] },
  {
    label: CountryName.Guinea,
    value: CountryNameToCodeMap[CountryName.Guinea],
  },
  {
    label: CountryName.GuineaBissau,
    value: CountryNameToCodeMap[CountryName.GuineaBissau],
  },
  {
    label: CountryName.IvoryCoast,
    value: CountryNameToCodeMap[CountryName.IvoryCoast],
  },
  { label: CountryName.Kenya, value: CountryNameToCodeMap[CountryName.Kenya] },
  {
    label: CountryName.Lesotho,
    value: CountryNameToCodeMap[CountryName.Lesotho],
  },
  {
    label: CountryName.Liberia,
    value: CountryNameToCodeMap[CountryName.Liberia],
  },
  { label: CountryName.Libya, value: CountryNameToCodeMap[CountryName.Libya] },
  {
    label: CountryName.Madagascar,
    value: CountryNameToCodeMap[CountryName.Madagascar],
  },
  {
    label: CountryName.Malawi,
    value: CountryNameToCodeMap[CountryName.Malawi],
  },
  { label: CountryName.Mali, value: CountryNameToCodeMap[CountryName.Mali] },
  {
    label: CountryName.Mauritania,
    value: CountryNameToCodeMap[CountryName.Mauritania],
  },
  {
    label: CountryName.Mauritius,
    value: CountryNameToCodeMap[CountryName.Mauritius],
  },
  {
    label: CountryName.Morocco,
    value: CountryNameToCodeMap[CountryName.Morocco],
  },
  {
    label: CountryName.Mozambique,
    value: CountryNameToCodeMap[CountryName.Mozambique],
  },
  {
    label: CountryName.Namibia,
    value: CountryNameToCodeMap[CountryName.Namibia],
  },
  { label: CountryName.Niger, value: CountryNameToCodeMap[CountryName.Niger] },
  {
    label: CountryName.Nigeria,
    value: CountryNameToCodeMap[CountryName.Nigeria],
  },
  {
    label: CountryName.Rwanda,
    value: CountryNameToCodeMap[CountryName.Rwanda],
  },
  {
    label: CountryName.SaoTomeAndPrincipe,
    value: CountryNameToCodeMap[CountryName.SaoTomeAndPrincipe],
  },
  {
    label: CountryName.Senegal,
    value: CountryNameToCodeMap[CountryName.Senegal],
  },
  {
    label: CountryName.Seychelles,
    value: CountryNameToCodeMap[CountryName.Seychelles],
  },
  {
    label: CountryName.SierraLeone,
    value: CountryNameToCodeMap[CountryName.SierraLeone],
  },
  {
    label: CountryName.Somalia,
    value: CountryNameToCodeMap[CountryName.Somalia],
  },
  {
    label: CountryName.SouthAfrica,
    value: CountryNameToCodeMap[CountryName.SouthAfrica],
  },
  {
    label: CountryName.SouthSudan,
    value: CountryNameToCodeMap[CountryName.SouthSudan],
  },
  { label: CountryName.Sudan, value: CountryNameToCodeMap[CountryName.Sudan] },
  {
    label: CountryName.Tanzania,
    value: CountryNameToCodeMap[CountryName.Tanzania],
  },
  { label: CountryName.Togo, value: CountryNameToCodeMap[CountryName.Togo] },
  {
    label: CountryName.Tunisia,
    value: CountryNameToCodeMap[CountryName.Tunisia],
  },
  {
    label: CountryName.Uganda,
    value: CountryNameToCodeMap[CountryName.Uganda],
  },
  {
    label: CountryName.Zambia,
    value: CountryNameToCodeMap[CountryName.Zambia],
  },
  {
    label: CountryName.Zimbabwe,
    value: CountryNameToCodeMap[CountryName.Zimbabwe],
  },
] as const;

export const asiaCountries = [
  {
    label: CountryName.Afghanistan,
    value: CountryNameToCodeMap[CountryName.Afghanistan],
  },
  {
    label: CountryName.Armenia,
    value: CountryNameToCodeMap[CountryName.Armenia],
  },
  {
    label: CountryName.Azerbaijan,
    value: CountryNameToCodeMap[CountryName.Azerbaijan],
  },
  {
    label: CountryName.Bahrain,
    value: CountryNameToCodeMap[CountryName.Bahrain],
  },
  {
    label: CountryName.Bangladesh,
    value: CountryNameToCodeMap[CountryName.Bangladesh],
  },
  {
    label: CountryName.Bhutan,
    value: CountryNameToCodeMap[CountryName.Bhutan],
  },
  {
    label: CountryName.Brunei,
    value: CountryNameToCodeMap[CountryName.Brunei],
  },
  {
    label: CountryName.Cambodia,
    value: CountryNameToCodeMap[CountryName.Cambodia],
  },
  { label: CountryName.China, value: CountryNameToCodeMap[CountryName.China] },
  {
    label: CountryName.Cyprus,
    value: CountryNameToCodeMap[CountryName.Cyprus],
  },
  {
    label: CountryName.Georgia,
    value: CountryNameToCodeMap[CountryName.Georgia],
  },
  { label: CountryName.India, value: CountryNameToCodeMap[CountryName.India] },
  {
    label: CountryName.Indonesia,
    value: CountryNameToCodeMap[CountryName.Indonesia],
  },
  { label: CountryName.Iran, value: CountryNameToCodeMap[CountryName.Iran] },
  { label: CountryName.Iraq, value: CountryNameToCodeMap[CountryName.Iraq] },
  {
    label: CountryName.Israel,
    value: CountryNameToCodeMap[CountryName.Israel],
  },
  { label: CountryName.Japan, value: CountryNameToCodeMap[CountryName.Japan] },
  {
    label: CountryName.Jordan,
    value: CountryNameToCodeMap[CountryName.Jordan],
  },
  {
    label: CountryName.Kazakhstan,
    value: CountryNameToCodeMap[CountryName.Kazakhstan],
  },
  {
    label: CountryName.Kuwait,
    value: CountryNameToCodeMap[CountryName.Kuwait],
  },
  {
    label: CountryName.Kyrgyzstan,
    value: CountryNameToCodeMap[CountryName.Kyrgyzstan],
  },
  { label: CountryName.Laos, value: CountryNameToCodeMap[CountryName.Laos] },
  {
    label: CountryName.Lebanon,
    value: CountryNameToCodeMap[CountryName.Lebanon],
  },
  {
    label: CountryName.Malaysia,
    value: CountryNameToCodeMap[CountryName.Malaysia],
  },
  {
    label: CountryName.Maldives,
    value: CountryNameToCodeMap[CountryName.Maldives],
  },
  {
    label: CountryName.Mongolia,
    value: CountryNameToCodeMap[CountryName.Mongolia],
  },
  {
    label: CountryName.Myanmar,
    value: CountryNameToCodeMap[CountryName.Myanmar],
  },
  { label: CountryName.Nepal, value: CountryNameToCodeMap[CountryName.Nepal] },
  {
    label: CountryName.NorthKorea,
    value: CountryNameToCodeMap[CountryName.NorthKorea],
  },
  { label: CountryName.Oman, value: CountryNameToCodeMap[CountryName.Oman] },
  {
    label: CountryName.Pakistan,
    value: CountryNameToCodeMap[CountryName.Pakistan],
  },
  {
    label: CountryName.PalestineState,
    value: CountryNameToCodeMap[CountryName.PalestineState],
  },
  {
    label: CountryName.Philippines,
    value: CountryNameToCodeMap[CountryName.Philippines],
  },
  { label: CountryName.Qatar, value: CountryNameToCodeMap[CountryName.Qatar] },
  {
    label: CountryName.SaudiArabia,
    value: CountryNameToCodeMap[CountryName.SaudiArabia],
  },
  {
    label: CountryName.Singapore,
    value: CountryNameToCodeMap[CountryName.Singapore],
  },
  {
    label: CountryName.SouthKorea,
    value: CountryNameToCodeMap[CountryName.SouthKorea],
  },
  {
    label: CountryName.SriLanka,
    value: CountryNameToCodeMap[CountryName.SriLanka],
  },
  { label: CountryName.Syria, value: CountryNameToCodeMap[CountryName.Syria] },
  {
    label: CountryName.Tajikistan,
    value: CountryNameToCodeMap[CountryName.Tajikistan],
  },
  {
    label: CountryName.Thailand,
    value: CountryNameToCodeMap[CountryName.Thailand],
  },
  {
    label: CountryName.TimorLeste,
    value: CountryNameToCodeMap[CountryName.TimorLeste],
  },
  {
    label: CountryName.Turkmenistan,
    value: CountryNameToCodeMap[CountryName.Turkmenistan],
  },
  { label: CountryName.UAE, value: CountryNameToCodeMap[CountryName.UAE] },
  {
    label: CountryName.Uzbekistan,
    value: CountryNameToCodeMap[CountryName.Uzbekistan],
  },
  {
    label: CountryName.Vietnam,
    value: CountryNameToCodeMap[CountryName.Vietnam],
  },
  { label: CountryName.Yemen, value: CountryNameToCodeMap[CountryName.Yemen] },
] as const;

export const europeCountries = [
  {
    label: CountryName.Albania,
    value: CountryNameToCodeMap[CountryName.Albania],
  },
  {
    label: CountryName.Andorra,
    value: CountryNameToCodeMap[CountryName.Andorra],
  },
  {
    label: CountryName.Armenia,
    value: CountryNameToCodeMap[CountryName.Armenia],
  },
  {
    label: CountryName.Austria,
    value: CountryNameToCodeMap[CountryName.Austria],
  },
  {
    label: CountryName.Azerbaijan,
    value: CountryNameToCodeMap[CountryName.Azerbaijan],
  },
  {
    label: CountryName.Belarus,
    value: CountryNameToCodeMap[CountryName.Belarus],
  },
  {
    label: CountryName.Belgium,
    value: CountryNameToCodeMap[CountryName.Belgium],
  },
  {
    label: CountryName.BosniaHerzegovina,
    value: CountryNameToCodeMap[CountryName.BosniaHerzegovina],
  },
  {
    label: CountryName.Bulgaria,
    value: CountryNameToCodeMap[CountryName.Bulgaria],
  },
  {
    label: CountryName.Croatia,
    value: CountryNameToCodeMap[CountryName.Croatia],
  },
  {
    label: CountryName.Cyprus,
    value: CountryNameToCodeMap[CountryName.Cyprus],
  },
  {
    label: CountryName.Czechia,
    value: CountryNameToCodeMap[CountryName.Czechia],
  },
  {
    label: CountryName.Denmark,
    value: CountryNameToCodeMap[CountryName.Denmark],
  },
  {
    label: CountryName.Estonia,
    value: CountryNameToCodeMap[CountryName.Estonia],
  },
  {
    label: CountryName.Finland,
    value: CountryNameToCodeMap[CountryName.Finland],
  },
  {
    label: CountryName.France,
    value: CountryNameToCodeMap[CountryName.France],
  },
  {
    label: CountryName.Georgia,
    value: CountryNameToCodeMap[CountryName.Georgia],
  },
  {
    label: CountryName.Germany,
    value: CountryNameToCodeMap[CountryName.Germany],
  },
  {
    label: CountryName.Greece,
    value: CountryNameToCodeMap[CountryName.Greece],
  },
  {
    label: CountryName.Hungary,
    value: CountryNameToCodeMap[CountryName.Hungary],
  },
  {
    label: CountryName.Iceland,
    value: CountryNameToCodeMap[CountryName.Iceland],
  },
  {
    label: CountryName.Ireland,
    value: CountryNameToCodeMap[CountryName.Ireland],
  },
  { label: CountryName.Italy, value: CountryNameToCodeMap[CountryName.Italy] },
  {
    label: CountryName.Kazakhstan,
    value: CountryNameToCodeMap[CountryName.Kazakhstan],
  },
  {
    label: CountryName.Kosovo,
    value: CountryNameToCodeMap[CountryName.Kosovo],
  },
  {
    label: CountryName.Latvia,
    value: CountryNameToCodeMap[CountryName.Latvia],
  },
  {
    label: CountryName.Liechtenstein,
    value: CountryNameToCodeMap[CountryName.Liechtenstein],
  },
  {
    label: CountryName.Lithuania,
    value: CountryNameToCodeMap[CountryName.Lithuania],
  },
  {
    label: CountryName.Luxembourg,
    value: CountryNameToCodeMap[CountryName.Luxembourg],
  },
  { label: CountryName.Malta, value: CountryNameToCodeMap[CountryName.Malta] },
  {
    label: CountryName.Moldova,
    value: CountryNameToCodeMap[CountryName.Moldova],
  },
  {
    label: CountryName.Monaco,
    value: CountryNameToCodeMap[CountryName.Monaco],
  },
  {
    label: CountryName.Montenegro,
    value: CountryNameToCodeMap[CountryName.Montenegro],
  },
  {
    label: CountryName.Netherlands,
    value: CountryNameToCodeMap[CountryName.Netherlands],
  },
  {
    label: CountryName.NorthMacedonia,
    value: CountryNameToCodeMap[CountryName.NorthMacedonia],
  },
  {
    label: CountryName.Norway,
    value: CountryNameToCodeMap[CountryName.Norway],
  },
  {
    label: CountryName.Poland,
    value: CountryNameToCodeMap[CountryName.Poland],
  },
  {
    label: CountryName.Portugal,
    value: CountryNameToCodeMap[CountryName.Portugal],
  },
  {
    label: CountryName.Romania,
    value: CountryNameToCodeMap[CountryName.Romania],
  },
  {
    label: CountryName.Russia,
    value: CountryNameToCodeMap[CountryName.Russia],
  },
  {
    label: CountryName.SanMarino,
    value: CountryNameToCodeMap[CountryName.SanMarino],
  },
  {
    label: CountryName.Serbia,
    value: CountryNameToCodeMap[CountryName.Serbia],
  },
  {
    label: CountryName.Slovakia,
    value: CountryNameToCodeMap[CountryName.Slovakia],
  },
  {
    label: CountryName.Slovenia,
    value: CountryNameToCodeMap[CountryName.Slovenia],
  },
  { label: CountryName.Spain, value: CountryNameToCodeMap[CountryName.Spain] },
  {
    label: CountryName.Sweden,
    value: CountryNameToCodeMap[CountryName.Sweden],
  },
  {
    label: CountryName.Switzerland,
    value: CountryNameToCodeMap[CountryName.Switzerland],
  },
  {
    label: CountryName.Turkey,
    value: CountryNameToCodeMap[CountryName.Turkey],
  },
  {
    label: CountryName.Ukraine,
    value: CountryNameToCodeMap[CountryName.Ukraine],
  },
  {
    label: CountryName.UnitedKingdom,
    value: CountryNameToCodeMap[CountryName.UnitedKingdom],
  },
] as const;

export const northAmericaCountries = [
  {
    label: CountryName.AntiguaAndBarbuda,
    value: CountryNameToCodeMap[CountryName.AntiguaAndBarbuda],
  },
  {
    label: CountryName.Bahamas,
    value: CountryNameToCodeMap[CountryName.Bahamas],
  },
  {
    label: CountryName.Barbados,
    value: CountryNameToCodeMap[CountryName.Barbados],
  },
  {
    label: CountryName.Belize,
    value: CountryNameToCodeMap[CountryName.Belize],
  },
  {
    label: CountryName.Canada,
    value: CountryNameToCodeMap[CountryName.Canada],
  },
  {
    label: CountryName.CostaRica,
    value: CountryNameToCodeMap[CountryName.CostaRica],
  },
  { label: CountryName.Cuba, value: CountryNameToCodeMap[CountryName.Cuba] },
  {
    label: CountryName.Dominica,
    value: CountryNameToCodeMap[CountryName.Dominica],
  },
  {
    label: CountryName.DominicanRepublic,
    value: CountryNameToCodeMap[CountryName.DominicanRepublic],
  },
  {
    label: CountryName.ElSalvador,
    value: CountryNameToCodeMap[CountryName.ElSalvador],
  },
  {
    label: CountryName.Grenada,
    value: CountryNameToCodeMap[CountryName.Grenada],
  },
  {
    label: CountryName.Guatemala,
    value: CountryNameToCodeMap[CountryName.Guatemala],
  },
  { label: CountryName.Haiti, value: CountryNameToCodeMap[CountryName.Haiti] },
  {
    label: CountryName.Honduras,
    value: CountryNameToCodeMap[CountryName.Honduras],
  },
  {
    label: CountryName.Jamaica,
    value: CountryNameToCodeMap[CountryName.Jamaica],
  },
  {
    label: CountryName.Mexico,
    value: CountryNameToCodeMap[CountryName.Mexico],
  },
  {
    label: CountryName.Nicaragua,
    value: CountryNameToCodeMap[CountryName.Nicaragua],
  },
  {
    label: CountryName.Panama,
    value: CountryNameToCodeMap[CountryName.Panama],
  },
  {
    label: CountryName.SaintKittsAndNevis,
    value: CountryNameToCodeMap[CountryName.SaintKittsAndNevis],
  },
  {
    label: CountryName.SaintLucia,
    value: CountryNameToCodeMap[CountryName.SaintLucia],
  },
  {
    label: CountryName.SaintVincentAndGrenadines,
    value: CountryNameToCodeMap[CountryName.SaintVincentAndGrenadines],
  },
  {
    label: CountryName.TrinidadAndTobago,
    value: CountryNameToCodeMap[CountryName.TrinidadAndTobago],
  },
  { label: CountryName.USA, value: CountryNameToCodeMap[CountryName.USA] },
] as const;

export const southAmericaCountries = [
  {
    label: CountryName.Argentina,
    value: CountryNameToCodeMap[CountryName.Argentina],
  },
  {
    label: CountryName.Bolivia,
    value: CountryNameToCodeMap[CountryName.Bolivia],
  },
  {
    label: CountryName.Brazil,
    value: CountryNameToCodeMap[CountryName.Brazil],
  },
  { label: CountryName.Chile, value: CountryNameToCodeMap[CountryName.Chile] },
  {
    label: CountryName.Colombia,
    value: CountryNameToCodeMap[CountryName.Colombia],
  },
  {
    label: CountryName.Ecuador,
    value: CountryNameToCodeMap[CountryName.Ecuador],
  },
  {
    label: CountryName.Guyana,
    value: CountryNameToCodeMap[CountryName.Guyana],
  },
  {
    label: CountryName.Paraguay,
    value: CountryNameToCodeMap[CountryName.Paraguay],
  },
  { label: CountryName.Peru, value: CountryNameToCodeMap[CountryName.Peru] },
  {
    label: CountryName.Suriname,
    value: CountryNameToCodeMap[CountryName.Suriname],
  },
  {
    label: CountryName.Uruguay,
    value: CountryNameToCodeMap[CountryName.Uruguay],
  },
  {
    label: CountryName.Venezuela,
    value: CountryNameToCodeMap[CountryName.Venezuela],
  },
] as const;

export const oceaniaCountries = [
  {
    label: CountryName.Australia,
    value: CountryNameToCodeMap[CountryName.Australia],
  },
  { label: CountryName.Fiji, value: CountryNameToCodeMap[CountryName.Fiji] },
  {
    label: CountryName.Kiribati,
    value: CountryNameToCodeMap[CountryName.Kiribati],
  },
  {
    label: CountryName.MarshallIslands,
    value: CountryNameToCodeMap[CountryName.MarshallIslands],
  },
  {
    label: CountryName.Micronesia,
    value: CountryNameToCodeMap[CountryName.Micronesia],
  },
  { label: CountryName.Nauru, value: CountryNameToCodeMap[CountryName.Nauru] },
  {
    label: CountryName.NewZealand,
    value: CountryNameToCodeMap[CountryName.NewZealand],
  },
  { label: CountryName.Palau, value: CountryNameToCodeMap[CountryName.Palau] },
  {
    label: CountryName.PapuaNewGuinea,
    value: CountryNameToCodeMap[CountryName.PapuaNewGuinea],
  },
  { label: CountryName.Samoa, value: CountryNameToCodeMap[CountryName.Samoa] },
  {
    label: CountryName.SolomonIslands,
    value: CountryNameToCodeMap[CountryName.SolomonIslands],
  },
  { label: CountryName.Tonga, value: CountryNameToCodeMap[CountryName.Tonga] },
  {
    label: CountryName.Tuvalu,
    value: CountryNameToCodeMap[CountryName.Tuvalu],
  },
  {
    label: CountryName.Vanuatu,
    value: CountryNameToCodeMap[CountryName.Vanuatu],
  },
] as const;

export const antarcticaCountries = [
  {
    label: CountryName.Antarctica,
    value: CountryNameToCodeMap[CountryName.Antarctica],
  },
] as const;

export function getCountriesByContinent(continent: Continents): readonly {
  label: string;
  value: CountryCode;
}[] {
  switch (continent) {
    case Continents.Africa:
      return africaCountries;
    case Continents.Asia:
      return asiaCountries;
    case Continents.Europe:
      return europeCountries;
    case Continents.NorthAmerica:
      return northAmericaCountries;
    case Continents.SouthAmerica:
      return southAmericaCountries;
    case Continents.Oceania:
      return oceaniaCountries;
    case Continents.Antarctica:
      return antarcticaCountries;
    default:
      return [] as {
        label: string;
        value: CountryCode;
      }[];
  }
}

export function getCountryNameByCodeFromSource(
  code: string,
  source?: readonly {
    label: string;
    value: string;
  }[],
): string | undefined {
  if (!source) {
    return undefined;
  }
  const country = source.find((country) => country.value === code);
  if (country) {
    return country.label;
  }
}

export function getCountryNameByCode(code: string): string {
  return (
    getCountryNameByCodeFromSource(code, africaCountries) ||
    getCountryNameByCodeFromSource(code, asiaCountries) ||
    getCountryNameByCodeFromSource(code, europeCountries) ||
    getCountryNameByCodeFromSource(code, northAmericaCountries) ||
    getCountryNameByCodeFromSource(code, southAmericaCountries) ||
    getCountryNameByCodeFromSource(code, oceaniaCountries) ||
    getCountryNameByCodeFromSource(code, antarcticaCountries) ||
    "Unknown Country"
  );
}

export const CountryCodeSchema = z.enum(countryCodes);
