/* eslint-disable @typescript-eslint/no-explicit-any */
import { z } from "zod";
import { CountryCode } from "./countries";

export const CurrencyCodes = {
  [CountryCode.Algeria]: "DZD",
  [CountryCode.Angola]: "AOA",
  [CountryCode.Antarctica]: "AAD",
  [CountryCode.Benin]: "XOF",
  [CountryCode.Botswana]: "BWP",
  [CountryCode.BurkinaFaso]: "XOF",
  [CountryCode.Burundi]: "BIF",
  [CountryCode.CaboVerde]: "CVE",
  [CountryCode.Cameroon]: "XAF",
  [CountryCode.CentralAfricanRepublic]: "XAF",
  [CountryCode.Chad]: "XAF",
  [CountryCode.Comoros]: "KMF",
  [CountryCode.CongoBrazzaville]: "XAF",
  [CountryCode.CongoKinshasa]: "CDF",
  [CountryCode.Djibouti]: "DJF",
  [CountryCode.Egypt]: "EGP",
  [CountryCode.EquatorialGuinea]: "XAF",
  [CountryCode.Eritrea]: "ERN",
  [CountryCode.Eswatini]: "SZL",
  [CountryCode.Ethiopia]: "ETB",
  [CountryCode.Gabon]: "XAF",
  [CountryCode.Gambia]: "GMD",
  [CountryCode.Ghana]: "GHS",
  [CountryCode.Guinea]: "GNF",
  [CountryCode.GuineaBissau]: "XOF",
  [CountryCode.IvoryCoast]: "XOF",
  [CountryCode.Kenya]: "KES",
  [CountryCode.Lesotho]: "LSL",
  [CountryCode.Liberia]: "LRD",
  [CountryCode.Libya]: "LYD",
  [CountryCode.Madagascar]: "MGA",
  [CountryCode.Malawi]: "MWK",
  [CountryCode.Mali]: "XOF",
  [CountryCode.Mauritania]: "MRU",
  [CountryCode.Mauritius]: "MUR",
  [CountryCode.Morocco]: "MAD",
  [CountryCode.Mozambique]: "MZN",
  [CountryCode.Namibia]: "NAD",
  [CountryCode.Niger]: "XOF",
  [CountryCode.Nigeria]: "NGN",
  [CountryCode.Rwanda]: "RWF",
  [CountryCode.SaoTomeAndPrincipe]: "STN",
  [CountryCode.Senegal]: "XOF",
  [CountryCode.Seychelles]: "SCR",
  [CountryCode.SierraLeone]: "SLL",
  [CountryCode.Somalia]: "SOS",
  [CountryCode.SouthAfrica]: "ZAR",
  [CountryCode.SouthSudan]: "SSP",
  [CountryCode.Sudan]: "SDG",
  [CountryCode.Tanzania]: "TZS",
  [CountryCode.Togo]: "XOF",
  [CountryCode.Tunisia]: "TND",
  [CountryCode.Uganda]: "UGX",
  [CountryCode.Zambia]: "ZMW",
  [CountryCode.Zimbabwe]: "ZWL",
  [CountryCode.Afghanistan]: "AFN",
  [CountryCode.Armenia]: "AMD",
  [CountryCode.Azerbaijan]: "AZN",
  [CountryCode.Bahrain]: "BHD",
  [CountryCode.Bangladesh]: "BDT",
  [CountryCode.Bhutan]: "BTN",
  [CountryCode.Brunei]: "BND",
  [CountryCode.Cambodia]: "KHR",
  [CountryCode.China]: "CNY",
  [CountryCode.Cyprus]: "EUR",
  [CountryCode.Georgia]: "GEL",
  [CountryCode.India]: "INR",
  [CountryCode.Indonesia]: "IDR",
  [CountryCode.Iran]: "IRR",
  [CountryCode.Iraq]: "IQD",
  [CountryCode.Israel]: "ILS",
  [CountryCode.Japan]: "JPY",
  [CountryCode.Jordan]: "JOD",
  [CountryCode.Kazakhstan]: "KZT",
  [CountryCode.Kuwait]: "KWD",
  [CountryCode.Kyrgyzstan]: "KGS",
  [CountryCode.Laos]: "LAK",
  [CountryCode.Lebanon]: "LBP",
  [CountryCode.Malaysia]: "MYR",
  [CountryCode.Maldives]: "MVR",
  [CountryCode.Mongolia]: "MNT",
  [CountryCode.Myanmar]: "MMK",
  [CountryCode.Nepal]: "NPR",
  [CountryCode.NorthKorea]: "KPW",
  [CountryCode.Oman]: "OMR",
  [CountryCode.Pakistan]: "PKR",
  [CountryCode.PalestineState]: "ILS",
  [CountryCode.Philippines]: "PHP",
  [CountryCode.Qatar]: "QAR",
  [CountryCode.SaudiArabia]: "SAR",
  [CountryCode.Singapore]: "SGD",
  [CountryCode.SouthKorea]: "KRW",
  [CountryCode.SriLanka]: "LKR",
  [CountryCode.Syria]: "SYP",
  [CountryCode.Tajikistan]: "TJS",
  [CountryCode.Thailand]: "THB",
  [CountryCode.TimorLeste]: "USD",
  [CountryCode.Turkmenistan]: "TMT",
  [CountryCode.UAE]: "AED",
  [CountryCode.Uzbekistan]: "UZS",
  [CountryCode.Vietnam]: "VND",
  [CountryCode.Yemen]: "YER",
  [CountryCode.Australia]: "AUD",
  [CountryCode.NewZealand]: "NZD",
  [CountryCode.USA]: "USD",
  [CountryCode.Canada]: "CAD",
  [CountryCode.Mexico]: "MXN",
  [CountryCode.Brazil]: "BRL",
  [CountryCode.Argentina]: "ARS",
  [CountryCode.Chile]: "CLP",
  [CountryCode.Colombia]: "COP",
  [CountryCode.Peru]: "PEN",
  [CountryCode.UnitedKingdom]: "GBP",
  [CountryCode.France]: "EUR",
  [CountryCode.Germany]: "EUR",
  [CountryCode.Italy]: "EUR",
  [CountryCode.Spain]: "EUR",
  [CountryCode.Russia]: "RUB",
  [CountryCode.Turkey]: "TRY",
} as const;

export type CurrencyCode = (typeof CurrencyCodes)[keyof typeof CurrencyCodes];
export const CurrencyCodeSchema = z
  .string()
  .refine((code) => Object.values(CurrencyCodes).includes(code as any), {
    message: "Invalid currency code",
  })
  .transform((v) => v as CurrencyCode);
